name: ci
on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            binPath: target/debug/trunk
            exPath: examples/yew/
          - os: macos-latest
            binPath: target/debug/trunk
            exPath: examples/yew/
          - os: windows-latest
            binPath: target\debug\trunk.exe
            exPath: examples\yew\
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: build
      # verify that we can actually execute the CLI and get some output
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- -h
      # build examples via our newly built debug artifact
      - run: ${{ matrix.binPath }} build ${{ matrix.exPath }}index.html --manifest-path=${{ matrix.exPath }}Cargo.toml
      # execute tests, including snapshot tests for the examples
      - uses: actions-rs/cargo@v1
        with:
          command: test
